"""Local density, current, source, and operator evaluation."""

from __future__ import annotations

from collections.abc import Sequence

import numpy as np
import numpy.typing as npt

from . import _core
from ._binding import call, complex_matrix, complex_vector


class LocalOperatorSet:
    """Rust-owned sparse local operator components.

    Component order follows the terms supplied to the constructor function.
    Matrix elements and applications operate directly on sparse native
    components; dense matrices are materialized only by explicit methods.
    """

    def __init__(self, native: object) -> None:
        if not isinstance(native, _core.LocalOperatorSet):
            raise TypeError("LocalOperatorSet objects are created by module functions")
        self._native = native

    @property
    def dimension(self) -> int:
        """Hilbert-space dimension on which all components act."""
        return int(self._native.dimension)

    def matrix_elements(
        self,
        bra: npt.ArrayLike,
        ket: npt.ArrayLike,
    ) -> np.ndarray:
        """Evaluate every component as ``braᴴ O_i ket``.

        Args:
            bra: Complex bra-state coefficients.
            ket: Complex ket-state coefficients.

        Returns:
            One complex matrix element per local component.
        """
        return np.asarray(
            call(
                self._native.matrix_elements,
                complex_vector(bra, name="bra").tolist(),
                complex_vector(ket, name="ket").tolist(),
            ),
            dtype=np.complex128,
        )

    def apply(self, ket: npt.ArrayLike) -> np.ndarray:
        """Apply the sum of all local components to ``ket``."""
        return np.asarray(
            call(
                self._native.apply_total,
                complex_vector(ket, name="ket").tolist(),
            ),
            dtype=np.complex128,
        )

    def matrix(self) -> np.ndarray:
        """Materialize the dense matrix of the summed operator."""
        return np.asarray(call(self._native.total_matrix), dtype=np.complex128)

    def component_matrices(self) -> np.ndarray:
        """Materialize every local component as a dense matrix stack."""
        return np.asarray(
            call(self._native.component_matrices),
            dtype=np.complex128,
        )


def densities(
    site_dimensions: Sequence[int],
    terms: Sequence[tuple[int, npt.ArrayLike]],
) -> LocalOperatorSet:
    """Construct site-local density operators.

    Args:
        site_dimensions: Number of internal states on every site.
        terms: ``(site, observable)`` records. Each observable acts in the
            local internal space of its zero-based site.

    Returns:
        Sparse component operators in the order supplied.
    """
    converted = [
        (int(site), complex_matrix(observable, name="observable").tolist())
        for site, observable in terms
    ]
    return LocalOperatorSet(
        call(
            _core.local_density_operators,
            [int(value) for value in site_dimensions],
            converted,
        )
    )


def currents(
    site_dimensions: Sequence[int],
    terms: Sequence[
        tuple[int, int, npt.ArrayLike, npt.ArrayLike]
    ],
) -> LocalOperatorSet:
    """Construct directed bond-current operators.

    Args:
        site_dimensions: Number of internal states on every site.
        terms: ``(site, neighbor, observable, hopping)`` records using
            zero-based site indices. ``hopping`` maps neighbor states into site
            states.

    Returns:
        Hermitian bond-current components in the order supplied.
    """
    converted = [
        (
            int(site),
            int(neighbor),
            complex_matrix(observable, name="observable").tolist(),
            complex_matrix(hopping, name="hopping").tolist(),
        )
        for site, neighbor, observable, hopping in terms
    ]
    return LocalOperatorSet(
        call(
            _core.bond_current_operators,
            [int(value) for value in site_dimensions],
            converted,
        )
    )


def sources(
    site_dimensions: Sequence[int],
    terms: Sequence[tuple[int, npt.ArrayLike, npt.ArrayLike]],
) -> LocalOperatorSet:
    """Construct onsite source terms for local continuity equations.

    Args:
        site_dimensions: Number of internal states on every site.
        terms: ``(site, observable, onsite)`` records for zero-based sites.

    Returns:
        Local source components generated by the onsite commutators.
    """
    converted = [
        (
            int(site),
            complex_matrix(observable, name="observable").tolist(),
            complex_matrix(onsite, name="onsite").tolist(),
        )
        for site, observable, onsite in terms
    ]
    return LocalOperatorSet(
        call(
            _core.local_source_operators,
            [int(value) for value in site_dimensions],
            converted,
        )
    )


def project_diagonal(
    states: npt.ArrayLike,
    diagonal: npt.ArrayLike,
) -> np.ndarray:
    """Project a diagonal observable into a supplied state basis.

    ``states`` stores basis vectors as columns and ``diagonal`` is expressed in
    the original basis. The result is ``statesᴴ diag(diagonal) states``.
    """
    return np.asarray(
        call(
            _core.diagonal_observable_matrix,
            complex_matrix(states, name="states").tolist(),
            np.asarray(diagonal, dtype=np.float64).tolist(),
        ),
        dtype=np.complex128,
    )


def pauli_coefficients(matrix: npt.ArrayLike) -> np.ndarray:
    """Decompose a matrix into tensor products of Pauli matrices.

    The matrix dimension must be a power of two. Returned coefficients follow
    lexicographic tensor-product order with ``(I, X, Y, Z)`` on each factor.
    """
    return np.asarray(
        call(
            _core.pauli_decompose,
            complex_matrix(matrix, name="matrix").tolist(),
        ),
        dtype=np.complex128,
    )


__all__ = [
    "LocalOperatorSet",
    "currents",
    "densities",
    "pauli_coefficients",
    "project_diagonal",
    "sources",
]
