#!/usr/bin/env python3
"""Generate and validate the committed language-neutral C ABI header."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "crates" / "thouless-capi" / "include" / "thouless.h"
SOURCES = sorted((ROOT / "crates" / "thouless-capi" / "src").glob("*.rs"))

HEADER = """\
/* Generated by tools/generate_c_header.py. Do not edit manually. */
#ifndef THOULESS_H
#define THOULESS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#if defined(_WIN32)
#  if defined(THOULESS_BUILDING_LIBRARY)
#    define THOULESS_API __declspec(dllexport)
#  else
#    define THOULESS_API __declspec(dllimport)
#  endif
#else
#  define THOULESS_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define THOULESS_ABI_VERSION_MAJOR 1u
#define THOULESS_ABI_VERSION_MINOR 0u
#define THOULESS_ABI_VERSION ((THOULESS_ABI_VERSION_MAJOR << 16) | THOULESS_ABI_VERSION_MINOR)

typedef enum ThoulessStatus {
    THOULESS_SUCCESS = 0,
    THOULESS_NULL_POINTER = 1,
    THOULESS_INVALID_ARGUMENT = 2,
    THOULESS_SHAPE_MISMATCH = 3,
    THOULESS_NUMERICAL_FAILURE = 4,
    THOULESS_UNSUPPORTED = 5,
    THOULESS_RESOURCE_EXHAUSTED = 6,
    THOULESS_PANIC = 7,
    THOULESS_BUFFER_TOO_SMALL = 8,
    THOULESS_INTERNAL_ERROR = 9
} ThoulessStatus;

typedef struct ThoulessComplex64 {
    double re;
    double im;
} ThoulessComplex64;

typedef struct ThoulessF64MatrixView {
    const double *data;
    size_t rows;
    size_t columns;
    size_t row_stride;
    size_t column_stride;
} ThoulessF64MatrixView;

typedef struct ThoulessC64MatrixView {
    const ThoulessComplex64 *data;
    size_t rows;
    size_t columns;
    size_t row_stride;
    size_t column_stride;
} ThoulessC64MatrixView;

typedef struct ThoulessF64MatrixMut {
    double *data;
    size_t rows;
    size_t columns;
    size_t row_stride;
    size_t column_stride;
} ThoulessF64MatrixMut;

typedef struct ThoulessC64MatrixMut {
    ThoulessComplex64 *data;
    size_t rows;
    size_t columns;
    size_t row_stride;
    size_t column_stride;
} ThoulessC64MatrixMut;

typedef struct ThoulessC64Tensor3View {
    const ThoulessComplex64 *data;
    size_t matrices;
    size_t rows;
    size_t columns;
    size_t matrix_stride;
    size_t row_stride;
    size_t column_stride;
} ThoulessC64Tensor3View;

typedef struct ThoulessC64Tensor3Mut {
    ThoulessComplex64 *data;
    size_t matrices;
    size_t rows;
    size_t columns;
    size_t matrix_stride;
    size_t row_stride;
    size_t column_stride;
} ThoulessC64Tensor3Mut;

typedef struct ThoulessLeadView {
    ThoulessC64MatrixView cell_hamiltonian;
    ThoulessC64MatrixView inter_cell_hopping;
    ThoulessC64MatrixView coupling;
} ThoulessLeadView;

typedef struct ThoulessModelBuilder ThoulessModelBuilder;
typedef struct ThoulessModel ThoulessModel;

THOULESS_API uint32_t thouless_abi_version(void);
THOULESS_API size_t thouless_last_error_length(void);
THOULESS_API ThoulessStatus thouless_last_error_copy(char *output, size_t capacity);

THOULESS_API ThoulessStatus thouless_model_builder_create(ThoulessF64MatrixView primitive_vectors, const size_t *periodic_axes, size_t periodic_axis_count, ThoulessModelBuilder **output);
THOULESS_API ThoulessStatus thouless_model_builder_destroy(ThoulessModelBuilder *handle);
THOULESS_API ThoulessStatus thouless_model_builder_add_orbital(ThoulessModelBuilder *handle, const uint8_t *label, size_t label_length, const double *reduced_position, size_t position_length, size_t degrees_of_freedom, size_t *output_orbital);
THOULESS_API ThoulessStatus thouless_model_builder_set_onsite(ThoulessModelBuilder *handle, size_t orbital_index, double energy);
THOULESS_API ThoulessStatus thouless_model_builder_set_onsite_block(ThoulessModelBuilder *handle, size_t orbital_index, ThoulessC64MatrixView block);
THOULESS_API ThoulessStatus thouless_model_builder_add_hopping(ThoulessModelBuilder *handle, size_t target, size_t source, const int32_t *cell_offset, size_t offset_length, ThoulessComplex64 amplitude);
THOULESS_API ThoulessStatus thouless_model_builder_add_hopping_block(ThoulessModelBuilder *handle, size_t target, size_t source, const int32_t *cell_offset, size_t offset_length, ThoulessC64MatrixView amplitude);
THOULESS_API ThoulessStatus thouless_model_builder_build(ThoulessModelBuilder *handle, ThoulessModel **output);
THOULESS_API ThoulessStatus thouless_model_destroy(ThoulessModel *handle);
THOULESS_API ThoulessStatus thouless_model_state_count(const ThoulessModel *handle, size_t *output);
THOULESS_API ThoulessStatus thouless_model_hamiltonian(const ThoulessModel *handle, const double *momentum, size_t momentum_length, ThoulessC64MatrixMut output);
THOULESS_API ThoulessStatus thouless_model_eigensystem(const ThoulessModel *handle, const double *momentum, size_t momentum_length, double *eigenvalues, size_t eigenvalue_capacity, ThoulessC64MatrixMut eigenvectors);
THOULESS_API ThoulessStatus thouless_model_finite_cluster(const ThoulessModel *handle, const int32_t *cells, size_t cell_count, size_t cell_dimension, ThoulessModel **output);
THOULESS_API ThoulessStatus thouless_model_finite_geometry(const ThoulessModel *handle, const int32_t *cells, const size_t *orbital_indices, size_t site_count, size_t cell_dimension, ThoulessModel **output);
THOULESS_API ThoulessStatus thouless_model_remove_orbitals(const ThoulessModel *handle, const size_t *removed, size_t removed_count, ThoulessModel **output);

THOULESS_API ThoulessStatus thouless_hermitian_eigensystem(ThoulessC64MatrixView matrix, double *eigenvalues, size_t eigenvalue_capacity, ThoulessC64MatrixMut eigenvectors);
THOULESS_API ThoulessStatus thouless_kpm_rescale_dense(ThoulessC64MatrixView hamiltonian, double strict_margin, bool use_explicit_bounds, double lower_bound, double upper_bound, ThoulessC64MatrixMut output, double *half_width, double *center);
THOULESS_API ThoulessStatus thouless_lead_bands(ThoulessC64MatrixView cell_hamiltonian, ThoulessC64MatrixView inter_cell_hopping, double momentum, size_t derivative_order, double *energies, size_t energy_capacity, double *first_derivatives, size_t first_capacity, double *second_derivatives, size_t second_capacity);
THOULESS_API ThoulessStatus thouless_bloch_phase(const int64_t *translation, size_t translation_length, const double *momentum, size_t momentum_length, ThoulessComplex64 *output);
THOULESS_API ThoulessStatus thouless_reciprocal_path(ThoulessF64MatrixView primitive_vectors, const size_t *periodic_axes, size_t periodic_axis_count, ThoulessF64MatrixView nodes, size_t sample_count, ThoulessF64MatrixMut points, double *distances, size_t distance_capacity, double *node_distances, size_t node_distance_capacity);
THOULESS_API ThoulessStatus thouless_continuum_momentum_stencil(size_t dimension, const size_t *axes, const size_t *powers, size_t factor_count, int32_t *offsets, uint32_t *inverse_spacing_powers, ThoulessComplex64 *weights, size_t term_capacity, size_t *term_count);
THOULESS_API ThoulessStatus thouless_interpolate_density(ThoulessF64MatrixView points, const double *values, size_t value_count, ThoulessF64MatrixView reference_starts, ThoulessF64MatrixView reference_ends, double absolute_width, size_t samples_per_width, size_t *shape, size_t shape_capacity, ThoulessF64MatrixMut bounds, double *output_values, size_t output_capacity, size_t *required_values);
THOULESS_API ThoulessStatus thouless_wilson_phase(ThoulessC64Tensor3View frames, double *output);
THOULESS_API ThoulessStatus thouless_model_chern_numbers(const ThoulessModel *model, const size_t *samples, size_t sample_count, size_t first_direction, size_t second_direction, const size_t *occupied_states, size_t occupied_count, double *output, size_t output_capacity, size_t *value_count);
THOULESS_API ThoulessStatus thouless_quantum_geometric_tensor(ThoulessC64MatrixView hamiltonian, ThoulessC64Tensor3View derivatives, const size_t *occupied_states, size_t occupied_count, ThoulessComplex64 *output, size_t output_capacity);
THOULESS_API ThoulessStatus thouless_local_chern_marker(ThoulessC64MatrixView hamiltonian, ThoulessF64MatrixView positions, const size_t *occupied_states, size_t occupied_count, double cell_area, double *output, size_t output_capacity);
THOULESS_API ThoulessStatus thouless_wannier_project_trials(ThoulessC64Tensor3View frames, ThoulessC64MatrixView trials, double singular_tolerance, ThoulessC64Tensor3Mut output);
THOULESS_API ThoulessStatus thouless_model_intrinsic_curvature(const ThoulessModel *model, const double *momentum, size_t momentum_length, double chemical_potential, double temperature, bool cartesian, double degeneracy_tolerance, ThoulessF64MatrixMut output);
THOULESS_API ThoulessStatus thouless_project_diagonal_observable(ThoulessC64MatrixView states, const double *diagonal, size_t diagonal_length, ThoulessC64MatrixMut output);
THOULESS_API ThoulessStatus thouless_open_system_transmissions(ThoulessC64MatrixView device_hamiltonian, const ThoulessLeadView *leads, size_t lead_count, double energy, double broadening, ThoulessF64MatrixMut output);
THOULESS_API ThoulessStatus thouless_lead_mode_count(ThoulessC64MatrixView cell_hamiltonian, ThoulessC64MatrixView inter_cell_hopping, size_t *mode_count, size_t *incoming_count);
THOULESS_API ThoulessStatus thouless_lead_modes(ThoulessC64MatrixView cell_hamiltonian, ThoulessC64MatrixView inter_cell_hopping, ThoulessC64MatrixMut wave_functions, double *velocities, size_t velocity_capacity, double *momenta, size_t momentum_capacity);
THOULESS_API ThoulessStatus thouless_lead_self_energy(ThoulessC64MatrixView cell_hamiltonian, ThoulessC64MatrixView inter_cell_hopping, double energy, double broadening, size_t maximum_rank, bool use_maximum_rank, ThoulessC64MatrixMut output);
THOULESS_API ThoulessStatus thouless_validate_chiral_symmetry(ThoulessC64MatrixView matrix, ThoulessC64MatrixView chiral, size_t *violation_count);
THOULESS_API ThoulessStatus thouless_particle_hole_basis(ThoulessC64MatrixView wave_functions, ThoulessC64MatrixView particle_hole, ThoulessC64MatrixMut output, size_t *ordering, size_t ordering_capacity);
THOULESS_API ThoulessStatus thouless_random_gaussian_matrix(size_t dimension, uint32_t symmetry, double variance, const double *real_components, size_t real_count, const double *imaginary_components, size_t imaginary_count, ThoulessC64MatrixMut output);
THOULESS_API ThoulessStatus thouless_digest_uniform(const uint8_t *input, size_t input_length, const uint8_t *salt, size_t salt_length, double *output);
THOULESS_API ThoulessStatus thouless_digest_gaussian(const uint8_t *input, size_t input_length, const uint8_t *salt, size_t salt_length, double *output);
THOULESS_API ThoulessStatus thouless_lll_reduce(ThoulessF64MatrixView basis, double reduction_parameter, ThoulessF64MatrixMut reduced_basis, int64_t *transformation, size_t transformation_capacity);
THOULESS_API ThoulessStatus thouless_graph_compress(size_t node_count, const int64_t *tails, const int64_t *heads, size_t edge_count, size_t *row_offsets, size_t row_offset_capacity, int64_t *neighbors, size_t neighbor_capacity);
THOULESS_API ThoulessStatus thouless_dense_schur(ThoulessC64MatrixView matrix, ThoulessC64MatrixMut form, ThoulessC64MatrixMut vectors, ThoulessComplex64 *eigenvalues, size_t eigenvalue_capacity);
THOULESS_API ThoulessStatus thouless_sparse_solve(size_t rows, size_t columns, const size_t *row_offsets, size_t row_offset_count, const size_t *column_indices, const ThoulessComplex64 *values, size_t nonzero_count, ThoulessC64MatrixView right_hand_side, ThoulessC64MatrixMut output);

#ifdef __cplusplus
}
#endif

#endif
"""


def exported_rust_symbols() -> set[str]:
    expression = re.compile(
        r'pub(?: unsafe)? extern "C" fn\s+(thouless_[A-Za-z0-9_]+)'
    )
    return {
        match.group(1)
        for path in SOURCES
        for match in expression.finditer(path.read_text(encoding="utf-8"))
    }


def declared_header_symbols() -> set[str]:
    return set(re.findall(r"\b(thouless_[a-z0-9_]+)\s*\(", HEADER))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    exported = exported_rust_symbols()
    declared = declared_header_symbols()
    if exported != declared:
        print(
            "C header symbol mismatch: "
            f"missing={sorted(exported - declared)}, extra={sorted(declared - exported)}",
            file=sys.stderr,
        )
        raise SystemExit(1)

    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != HEADER:
            print(
                "committed C header is stale; run tools/generate_c_header.py",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print(f"validated generated C header with {len(exported)} exported functions")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(HEADER, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)} with {len(exported)} functions")


if __name__ == "__main__":
    main()
