//! Kernel-polynomial spectral and response primitives.
//!
//! The routines in this module operate on scientific objects rather than on a
//! compatibility-layer class.  A Hamiltonian is rescaled once, Chebyshev
//! vectors are generated by a stable three-term recurrence, and scalar or
//! vector-valued moments are reconstructed on Chebyshev nodes.

use std::error::Error;
use std::f64::consts::PI;
use std::fmt;

use nalgebra::{DMatrix, SymmetricEigen};

use crate::linear_operator::{CsrMatrix, LinearOperator, LinearOperatorError};
use crate::spectrum::hermitian_eigensystem;
use crate::{Complex64, ComplexMatrix};

const HERMITIAN_TOLERANCE: f64 = 1.0e-10;

/// Affine transformation from physical energy to the Chebyshev interval.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpectralScale {
    half_width: f64,
    center: f64,
}

impl SpectralScale {
    /// Creates an energy scale.
    pub fn new(half_width: f64, center: f64) -> Result<Self, KpmError> {
        if !half_width.is_finite() || half_width <= 0.0 || !center.is_finite() {
            return Err(KpmError::InvalidScale);
        }
        Ok(Self { half_width, center })
    }

    /// Multiplicative energy scale.
    #[must_use]
    pub const fn half_width(self) -> f64 {
        self.half_width
    }

    /// Center of the physical energy interval.
    #[must_use]
    pub const fn center(self) -> f64 {
        self.center
    }

    /// Maps a physical energy to the rescaled interval.
    #[must_use]
    pub fn rescale(self, energy: f64) -> f64 {
        (energy - self.center) / self.half_width
    }

    /// Maps a rescaled energy back to physical units.
    #[must_use]
    pub fn physical(self, rescaled_energy: f64) -> f64 {
        self.half_width.mul_add(rescaled_energy, self.center)
    }
}

/// A rescaled Hamiltonian together with its energy transformation.
#[derive(Clone, Debug, PartialEq)]
pub struct RescaledHamiltonian {
    matrix: ComplexMatrix,
    scale: SpectralScale,
}

impl RescaledHamiltonian {
    /// Rescaled dense matrix whose spectrum lies strictly within `(-1, 1)`.
    #[must_use]
    pub const fn matrix(&self) -> &ComplexMatrix {
        &self.matrix
    }

    /// Physical-to-rescaled energy transformation.
    #[must_use]
    pub const fn scale(&self) -> SpectralScale {
        self.scale
    }
}

/// A matrix-free Hamiltonian transformed into the Chebyshev interval.
#[derive(Clone, Debug, PartialEq)]
pub struct RescaledLinearOperator<O> {
    operator: O,
    scale: SpectralScale,
}

impl<O: LinearOperator> RescaledLinearOperator<O> {
    /// Creates an affine view `(H - center I) / half_width`.
    pub fn new(operator: O, scale: SpectralScale) -> Result<Self, KpmError> {
        validate_operator_square(&operator)?;
        Ok(Self { operator, scale })
    }

    /// Original, unscaled operator.
    #[must_use]
    pub const fn operator(&self) -> &O {
        &self.operator
    }

    /// Physical-to-rescaled energy transformation.
    #[must_use]
    pub const fn scale(&self) -> SpectralScale {
        self.scale
    }
}

impl<O: LinearOperator> LinearOperator for RescaledLinearOperator<O> {
    fn rows(&self) -> usize {
        self.operator.rows()
    }

    fn columns(&self) -> usize {
        self.operator.columns()
    }

    fn apply_into(
        &self,
        input: &[Complex64],
        output: &mut [Complex64],
    ) -> Result<(), LinearOperatorError> {
        self.operator.apply_into(input, output)?;
        for (value, input_value) in output.iter_mut().zip(input) {
            *value = (*value - *input_value * self.scale.center()) / self.scale.half_width();
        }
        if output
            .iter()
            .any(|value| !value.re.is_finite() || !value.im.is_finite())
        {
            Err(LinearOperatorError::NonFiniteValue)
        } else {
            Ok(())
        }
    }
}

/// Controls the matrix-free Lanczos estimate of extremal eigenvalues.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct LanczosOptions {
    /// Maximum Krylov-subspace dimension.
    pub max_iterations: usize,
    /// Relative residual required for both extremal Ritz pairs.
    pub relative_tolerance: f64,
}

/// Extremal Ritz values and their final Lanczos residuals.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpectralBounds {
    /// Smallest estimated eigenvalue.
    pub lower: f64,
    /// Largest estimated eigenvalue.
    pub upper: f64,
    /// Residual norm of the smallest Ritz pair.
    pub lower_residual: f64,
    /// Residual norm of the largest Ritz pair.
    pub upper_residual: f64,
    /// Krylov-subspace dimension used.
    pub iterations: usize,
    /// Whether both residuals reached the requested tolerance.
    pub converged: bool,
    /// Whether the recurrence terminated in a proper invariant subspace.
    pub breakdown: bool,
}

/// A reconstructed spectral function.
///
/// Both `densities` and `gammas` use the layout
/// `[sampling_point][channel][component]`.  A mean calculation has one
/// channel; otherwise each stochastic or local vector has its own channel.
#[derive(Clone, Debug, PartialEq)]
pub struct SpectralReconstruction {
    energies: Vec<f64>,
    densities: Vec<Vec<Vec<Complex64>>>,
    gammas: Vec<Vec<Vec<Complex64>>>,
    moments: Vec<Vec<Vec<Complex64>>>,
}

impl SpectralReconstruction {
    /// Physical sampling energies in ascending order.
    #[must_use]
    pub fn energies(&self) -> &[f64] {
        &self.energies
    }

    /// Spectral values at the sampling energies.
    #[must_use]
    pub fn densities(&self) -> &[Vec<Vec<Complex64>>] {
        &self.densities
    }

    /// Chebyshev numerators before division by the square-root weight.
    #[must_use]
    pub fn gammas(&self) -> &[Vec<Vec<Complex64>>] {
        &self.gammas
    }

    /// Stabilized moments with layout `[moment][channel][component]`.
    #[must_use]
    pub fn moments(&self) -> &[Vec<Vec<Complex64>>] {
        &self.moments
    }
}

/// Stabilization kernel for a truncated Chebyshev expansion.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Kernel {
    /// Jackson damping, appropriate for positive spectral densities.
    Jackson,
    /// Lorentz damping with the supplied decay strength.
    Lorentz(f64),
    /// No damping.
    None,
}

/// Errors raised by kernel-polynomial calculations.
#[derive(Clone, Debug, PartialEq)]
#[non_exhaustive]
pub enum KpmError {
    /// The Hamiltonian is empty or not square.
    InvalidHamiltonianShape {
        /// Number of rows.
        rows: usize,
        /// Number of columns.
        columns: usize,
    },
    /// The Hamiltonian is not Hermitian.
    NonHermitianHamiltonian,
    /// The strict-bound margin is not in `(0, 2)`.
    InvalidMargin,
    /// User-provided spectral bounds are invalid.
    InvalidBounds,
    /// The Hamiltonian has no nonzero spectral width.
    SingleEigenvalue,
    /// A scale is non-finite or has non-positive width.
    InvalidScale,
    /// At least one Chebyshev moment is required.
    NoMoments,
    /// At least one input vector is required.
    NoVectors,
    /// A vector has an incompatible dimension.
    VectorDimension {
        /// Required dimension.
        expected: usize,
        /// Supplied dimension.
        actual: usize,
    },
    /// Nested moment or vector data is ragged.
    RaggedData,
    /// An operator matrix has an incompatible shape.
    OperatorShape {
        /// Required dimension.
        expected: usize,
        /// Number of rows.
        rows: usize,
        /// Number of columns.
        columns: usize,
    },
    /// The dense Hermitian eigensolver failed.
    EigensystemFailure,
    /// A numerical input is not finite.
    NonFiniteValue,
    /// A matrix-free operator could not be constructed or applied.
    LinearOperator(LinearOperatorError),
    /// Lanczos options do not define a finite, nonempty iteration.
    InvalidLanczosOptions,
}

impl fmt::Display for KpmError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidHamiltonianShape { rows, columns } => {
                write!(
                    formatter,
                    "Hamiltonian shape ({rows}, {columns}) is not a non-empty square"
                )
            }
            Self::NonHermitianHamiltonian => write!(formatter, "Hamiltonian is not Hermitian"),
            Self::InvalidMargin => write!(formatter, "strict-bound margin must lie in (0, 2)"),
            Self::InvalidBounds => {
                write!(formatter, "spectral bounds must be finite and increasing")
            }
            Self::SingleEigenvalue => write!(
                formatter,
                "Hamiltonian has a single eigenvalue, so a spectral density cannot be constructed"
            ),
            Self::InvalidScale => write!(formatter, "spectral scale must be finite and positive"),
            Self::NoMoments => write!(formatter, "at least one Chebyshev moment is required"),
            Self::NoVectors => write!(formatter, "at least one sampling vector is required"),
            Self::VectorDimension { expected, actual } => write!(
                formatter,
                "sampling vector has dimension {actual}, expected {expected}"
            ),
            Self::RaggedData => write!(formatter, "nested KPM data has inconsistent dimensions"),
            Self::OperatorShape {
                expected,
                rows,
                columns,
            } => write!(
                formatter,
                "operator shape ({rows}, {columns}) is incompatible with dimension {expected}"
            ),
            Self::EigensystemFailure => write!(formatter, "Hamiltonian eigensystem failed"),
            Self::NonFiniteValue => write!(formatter, "KPM input contains a non-finite value"),
            Self::LinearOperator(error) => write!(formatter, "linear-operator failure: {error}"),
            Self::InvalidLanczosOptions => {
                write!(
                    formatter,
                    "Lanczos options must define a positive finite iteration"
                )
            }
        }
    }
}

impl Error for KpmError {}

impl From<LinearOperatorError> for KpmError {
    fn from(error: LinearOperatorError) -> Self {
        Self::LinearOperator(error)
    }
}

/// Rescales a dense Hermitian Hamiltonian into the open Chebyshev interval.
pub fn rescale_hamiltonian(
    hamiltonian: &ComplexMatrix,
    strict_margin: f64,
    bounds: Option<(f64, f64)>,
) -> Result<RescaledHamiltonian, KpmError> {
    let (rows, columns) = hamiltonian.shape();
    if rows == 0 || rows != columns {
        return Err(KpmError::InvalidHamiltonianShape { rows, columns });
    }
    if !hamiltonian
        .is_hermitian(HERMITIAN_TOLERANCE)
        .map_err(|_| KpmError::InvalidHamiltonianShape { rows, columns })?
    {
        return Err(KpmError::NonHermitianHamiltonian);
    }
    if !strict_margin.is_finite() || strict_margin <= 0.0 || strict_margin >= 2.0 {
        return Err(KpmError::InvalidMargin);
    }
    let (lower, upper) = match bounds {
        Some((lower, upper)) if lower.is_finite() && upper.is_finite() && lower < upper => {
            (lower, upper)
        }
        Some(_) => return Err(KpmError::InvalidBounds),
        None => {
            let eigensystem = hermitian_eigensystem(hamiltonian, HERMITIAN_TOLERANCE)
                .map_err(|_| KpmError::EigensystemFailure)?;
            (
                *eigensystem
                    .eigenvalues()
                    .first()
                    .ok_or(KpmError::SingleEigenvalue)?,
                *eigensystem
                    .eigenvalues()
                    .last()
                    .ok_or(KpmError::SingleEigenvalue)?,
            )
        }
    };
    let scale = spectral_scale(lower, upper, strict_margin)?;
    let data = hamiltonian
        .as_slice()
        .iter()
        .enumerate()
        .map(|(index, value)| {
            let row = index / columns;
            let column = index % columns;
            let shifted = if row == column {
                *value - Complex64::new(scale.center(), 0.0)
            } else {
                *value
            };
            shifted / scale.half_width()
        })
        .collect();
    let matrix = ComplexMatrix::new(rows, columns, data).map_err(|_| KpmError::NonFiniteValue)?;
    Ok(RescaledHamiltonian { matrix, scale })
}

/// Estimates the spectral extremes of a Hermitian matrix-free operator.
///
/// The implementation stores only the three recurrence vectors and the small
/// real symmetric tridiagonal projection. It therefore scales with the
/// operator storage rather than with the square of its dimension.
pub fn estimate_spectral_bounds<O: LinearOperator + ?Sized>(
    operator: &O,
    initial_vector: &[Complex64],
    options: LanczosOptions,
) -> Result<SpectralBounds, KpmError> {
    let dimension = validate_operator_square(operator)?;
    if options.max_iterations == 0
        || !options.relative_tolerance.is_finite()
        || options.relative_tolerance <= 0.0
    {
        return Err(KpmError::InvalidLanczosOptions);
    }
    validate_vectors(&[initial_vector.to_vec()], dimension)?;
    let initial_norm = norm(initial_vector);
    if !initial_norm.is_finite() || initial_norm == 0.0 {
        return Err(KpmError::NonFiniteValue);
    }

    let maximum = options.max_iterations.min(dimension);
    let mut previous = vec![Complex64::new(0.0, 0.0); dimension];
    let mut current = initial_vector
        .iter()
        .map(|value| *value / initial_norm)
        .collect::<Vec<_>>();
    let mut beta_previous = 0.0;
    let mut alphas = Vec::with_capacity(maximum);
    let mut betas = Vec::with_capacity(maximum.saturating_sub(1));
    let mut latest = None;

    for iteration in 0..maximum {
        let mut next = operator.apply(&current)?;
        if iteration > 0 {
            for (value, old) in next.iter_mut().zip(&previous) {
                *value -= *old * beta_previous;
            }
        }
        let alpha_complex = inner(&current, &next);
        let scale = norm(&next).max(1.0);
        if alpha_complex.im.abs() > HERMITIAN_TOLERANCE * scale {
            return Err(KpmError::NonHermitianHamiltonian);
        }
        let alpha = alpha_complex.re;
        for (value, basis) in next.iter_mut().zip(&current) {
            *value -= *basis * alpha;
        }
        let beta = norm(&next);
        alphas.push(alpha);

        let may_stop_on_residual = maximum < dimension;
        let recurrence_scale = alpha.abs().max(beta_previous).max(1.0);
        let breakdown = beta <= f64::EPSILON.sqrt() * recurrence_scale;
        let final_iteration = iteration + 1 == maximum;
        let inspect_residual = may_stop_on_residual && (iteration + 1) % 8 == 0;
        if breakdown || final_iteration || inspect_residual {
            let projection = tridiagonal_extremes(&alphas, &betas, beta)?;
            let spectral_scale = projection.lower.abs().max(projection.upper.abs()).max(1.0);
            let converged = projection.lower_residual
                <= options.relative_tolerance * spectral_scale
                && projection.upper_residual <= options.relative_tolerance * spectral_scale;
            latest = Some(SpectralBounds {
                iterations: iteration + 1,
                converged,
                breakdown,
                ..projection
            });
            if (may_stop_on_residual && converged) || breakdown || final_iteration {
                break;
            }
        }

        betas.push(beta);
        previous = current;
        current = next.into_iter().map(|value| value / beta).collect();
        beta_previous = beta;
    }

    latest.ok_or(KpmError::EigensystemFailure)
}

/// Rescales a canonical CSR Hermitian Hamiltonian without dense materialization.
///
/// Explicit bounds are used verbatim. Otherwise a Lanczos estimate is used
/// when its extremal residuals converge; a conservative Gershgorin enclosure
/// is the deterministic fallback.
pub fn rescale_sparse_hamiltonian(
    hamiltonian: CsrMatrix,
    strict_margin: f64,
    bounds: Option<(f64, f64)>,
    initial_vector: &[Complex64],
) -> Result<RescaledLinearOperator<CsrMatrix>, KpmError> {
    let dimension = validate_operator_square(&hamiltonian)?;
    if !hamiltonian.is_hermitian(HERMITIAN_TOLERANCE)? {
        return Err(KpmError::NonHermitianHamiltonian);
    }
    if !strict_margin.is_finite() || strict_margin <= 0.0 || strict_margin >= 2.0 {
        return Err(KpmError::InvalidMargin);
    }
    let (lower, upper) = match bounds {
        Some((lower, upper)) if lower.is_finite() && upper.is_finite() && lower < upper => {
            (lower, upper)
        }
        Some(_) => return Err(KpmError::InvalidBounds),
        None => {
            let estimate = estimate_spectral_bounds(
                &hamiltonian,
                initial_vector,
                LanczosOptions {
                    max_iterations: dimension.min(256),
                    relative_tolerance: strict_margin / 4.0,
                },
            )?;
            if (estimate.converged && !estimate.breakdown) || estimate.iterations == dimension {
                (
                    estimate.lower - estimate.lower_residual,
                    estimate.upper + estimate.upper_residual,
                )
            } else {
                hamiltonian.gershgorin_bounds()?
            }
        }
    };
    let scale = spectral_scale(lower, upper, strict_margin)?;
    RescaledLinearOperator::new(hamiltonian, scale)
}

/// Generates `T_n(H)|r>` for each initial vector.
pub fn chebyshev_vectors<O: LinearOperator + ?Sized>(
    rescaled_hamiltonian: &O,
    initial_vectors: &[Vec<Complex64>],
    moment_count: usize,
) -> Result<Vec<Vec<Vec<Complex64>>>, KpmError> {
    let dimension = validate_operator_square(rescaled_hamiltonian)?;
    if moment_count == 0 {
        return Err(KpmError::NoMoments);
    }
    if initial_vectors.is_empty() {
        return Err(KpmError::NoVectors);
    }
    validate_vectors(initial_vectors, dimension)?;
    let mut result = Vec::with_capacity(initial_vectors.len());
    for initial in initial_vectors {
        let mut moments = Vec::with_capacity(moment_count);
        moments.push(initial.clone());
        if moment_count > 1 {
            moments.push(rescaled_hamiltonian.apply(initial)?);
        }
        while moments.len() < moment_count {
            let current = moments.last().expect("at least one moment");
            let previous = &moments[moments.len() - 2];
            let applied = rescaled_hamiltonian.apply(current)?;
            moments.push(
                applied
                    .into_iter()
                    .zip(previous)
                    .map(|(value, old)| value * 2.0 - old)
                    .collect(),
            );
        }
        result.push(moments);
    }
    Ok(result)
}

/// Computes scalar density-of-states moments from Chebyshev vectors.
pub fn scalar_moments(
    initial_vectors: &[Vec<Complex64>],
    chebyshev: &[Vec<Vec<Complex64>>],
    operator: Option<&ComplexMatrix>,
) -> Result<Vec<Vec<Vec<Complex64>>>, KpmError> {
    scalar_moments_with_operator(initial_vectors, chebyshev, operator)
}

/// Computes scalar moments with any matrix-free observation operator.
pub fn scalar_moments_with_operator<O: LinearOperator + ?Sized>(
    initial_vectors: &[Vec<Complex64>],
    chebyshev: &[Vec<Vec<Complex64>>],
    operator: Option<&O>,
) -> Result<Vec<Vec<Vec<Complex64>>>, KpmError> {
    let (vector_count, moment_count, dimension) = validate_chebyshev(chebyshev)?;
    validate_vectors(initial_vectors, dimension)?;
    if initial_vectors.len() != vector_count {
        return Err(KpmError::RaggedData);
    }
    if let Some(operator) = operator {
        if operator.shape() != (dimension, dimension) {
            return Err(KpmError::OperatorShape {
                expected: dimension,
                rows: operator.rows(),
                columns: operator.columns(),
            });
        }
    }
    let mut result = vec![vec![vec![Complex64::new(0.0, 0.0); 1]; moment_count]; vector_count];
    for vector in 0..vector_count {
        for moment in 0..moment_count {
            let ket = if let Some(operator) = operator {
                operator.apply(&chebyshev[vector][moment])?
            } else {
                chebyshev[vector][moment].clone()
            };
            result[vector][moment][0] = inner(&initial_vectors[vector], &ket);
        }
    }
    Ok(result)
}

/// Applies a linear operator to each vector in a Chebyshev-vector collection.
pub fn apply_operator_to_chebyshev<O: LinearOperator + ?Sized>(
    operator: &O,
    chebyshev: &[Vec<Vec<Complex64>>],
) -> Result<Vec<Vec<Vec<Complex64>>>, KpmError> {
    let (_, _, dimension) = validate_chebyshev(chebyshev)?;
    if operator.shape() != (dimension, dimension) {
        return Err(KpmError::OperatorShape {
            expected: dimension,
            rows: operator.rows(),
            columns: operator.columns(),
        });
    }
    chebyshev
        .iter()
        .map(|moments| {
            moments
                .iter()
                .map(|vector| operator.apply(vector).map_err(KpmError::from))
                .collect::<Result<Vec<_>, _>>()
        })
        .collect::<Result<Vec<_>, _>>()
}

/// Reconstructs a spectral function from raw vector-resolved moments.
pub fn reconstruct(
    raw_moments: &[Vec<Vec<Complex64>>],
    scale: SpectralScale,
    kernel: Kernel,
    mean: bool,
) -> Result<SpectralReconstruction, KpmError> {
    let (vector_count, moment_count, component_count) = validate_moments(raw_moments)?;
    let channel_count = if mean { 1 } else { vector_count };
    let weights = kernel_weights(moment_count, kernel)?;
    let mut moments =
        vec![vec![vec![Complex64::new(0.0, 0.0); component_count]; channel_count]; moment_count];
    for moment in 0..moment_count {
        for component in 0..component_count {
            if mean {
                let sum = raw_moments
                    .iter()
                    .map(|values| values[moment][component])
                    .sum::<Complex64>();
                moments[moment][0][component] =
                    sum / (vector_count as f64 * scale.half_width()) * weights[moment];
            } else {
                for (vector, raw_vector) in raw_moments.iter().enumerate() {
                    moments[moment][vector][component] =
                        raw_vector[moment][component] / scale.half_width() * weights[moment];
                }
            }
        }
    }

    reconstruct_stabilized(&moments, scale)
}

/// Reconstructs a spectral function from moments that already include scaling
/// and a user-selected stabilization kernel.
pub fn reconstruct_stabilized(
    moments: &[Vec<Vec<Complex64>>],
    scale: SpectralScale,
) -> Result<SpectralReconstruction, KpmError> {
    let (moment_count, channel_count, component_count) = validate_stabilized_moments(moments)?;
    let rescaled_nodes = chebyshev_nodes(2 * moment_count)?;
    let energies = rescaled_nodes
        .iter()
        .map(|energy| scale.physical(*energy))
        .collect::<Vec<_>>();
    let mut gammas = vec![
        vec![vec![Complex64::new(0.0, 0.0); component_count]; channel_count];
        rescaled_nodes.len()
    ];
    let mut densities = gammas.clone();
    for (sample, &energy) in rescaled_nodes.iter().enumerate() {
        for channel in 0..channel_count {
            for component in 0..component_count {
                let gamma = evaluate_series(moments, channel, component, energy);
                gammas[sample][channel][component] = gamma;
                densities[sample][channel][component] =
                    gamma / (PI * (1.0 - energy * energy).sqrt());
            }
        }
    }
    Ok(SpectralReconstruction {
        energies,
        densities,
        gammas,
        moments: moments.to_vec(),
    })
}

/// Evaluates stabilized moments at arbitrary physical energies.
pub fn evaluate(
    stabilized_moments: &[Vec<Vec<Complex64>>],
    scale: SpectralScale,
    energies: &[f64],
) -> Result<Vec<Vec<Vec<Complex64>>>, KpmError> {
    let (moment_count, channel_count, component_count) =
        validate_stabilized_moments(stabilized_moments)?;
    if moment_count == 0 {
        return Err(KpmError::NoMoments);
    }
    let mut values =
        vec![vec![vec![Complex64::new(0.0, 0.0); component_count]; channel_count]; energies.len()];
    for (sample, &physical_energy) in energies.iter().enumerate() {
        if !physical_energy.is_finite() {
            return Err(KpmError::NonFiniteValue);
        }
        let energy = scale.rescale(physical_energy);
        let denominator = PI * ((1.0 - energy) * (1.0 + energy)).sqrt();
        for (channel, channel_values) in values[sample].iter_mut().enumerate() {
            for (component, value) in channel_values.iter_mut().enumerate() {
                *value =
                    evaluate_series(stabilized_moments, channel, component, energy) / denominator;
            }
        }
    }
    Ok(values)
}

/// Integrates Chebyshev numerators using the corresponding quadrature.
pub fn integrate(
    gammas: &[Vec<Vec<Complex64>>],
    distribution: &[f64],
    scale: SpectralScale,
) -> Result<Vec<Vec<Complex64>>, KpmError> {
    let sample_count = gammas.len();
    if sample_count == 0 || distribution.len() != sample_count {
        return Err(KpmError::RaggedData);
    }
    let channel_count = gammas[0].len();
    let component_count = gammas[0].first().map_or(0, Vec::len);
    if channel_count == 0
        || component_count == 0
        || gammas.iter().any(|sample| {
            sample.len() != channel_count
                || sample
                    .iter()
                    .any(|channel| channel.len() != component_count)
        })
        || distribution.iter().any(|value| !value.is_finite())
    {
        return Err(KpmError::RaggedData);
    }
    let factor = scale.half_width() / sample_count as f64;
    let mut result = vec![vec![Complex64::new(0.0, 0.0); component_count]; channel_count];
    for (sample, &distribution_value) in gammas.iter().zip(distribution) {
        for (result_channel, sample_channel) in result.iter_mut().zip(sample) {
            for (result_component, &gamma) in result_channel.iter_mut().zip(sample_channel) {
                *result_component += gamma * distribution_value * factor;
            }
        }
    }
    Ok(result)
}

/// Computes vector-resolved two-dimensional Chebyshev moments.
pub fn correlation_moments(
    left: &[Vec<Vec<Complex64>>],
    right: &[Vec<Vec<Complex64>>],
    mean: bool,
) -> Result<Vec<Vec<Vec<Complex64>>>, KpmError> {
    let (vectors, moments, dimension) = validate_chebyshev(left)?;
    let (right_vectors, right_moments, right_dimension) = validate_chebyshev(right)?;
    if (vectors, moments, dimension) != (right_vectors, right_moments, right_dimension) {
        return Err(KpmError::RaggedData);
    }
    let channels = if mean { 1 } else { vectors };
    let mut result = vec![vec![vec![Complex64::new(0.0, 0.0); moments]; moments]; channels];
    for vector in 0..vectors {
        let channel = if mean { 0 } else { vector };
        for left_moment in 0..moments {
            for right_moment in 0..moments {
                result[channel][left_moment][right_moment] +=
                    inner(&left[vector][left_moment], &right[vector][right_moment])
                        / if mean { vectors as f64 } else { 1.0 };
            }
        }
    }
    Ok(result)
}

/// Builds the energy-dependent Kubo-Bastin integral factor.
pub fn correlation_integral_factor(
    moments: &[Vec<Vec<Complex64>>],
    moment_count: usize,
    kernel: Kernel,
) -> Result<Vec<Vec<Complex64>>, KpmError> {
    if moments.is_empty()
        || moment_count == 0
        || moments.iter().any(|channel| {
            channel.len() != moment_count || channel.iter().any(|row| row.len() != moment_count)
        })
    {
        return Err(KpmError::RaggedData);
    }
    let weights = kernel_weights(moment_count, kernel)?;
    let nodes = chebyshev_nodes(2 * moment_count)?;
    let mut result = vec![vec![Complex64::new(0.0, 0.0); moments.len()]; nodes.len()];
    for (sample, energy) in nodes.into_iter().enumerate() {
        let angle = energy.acos();
        let root = (1.0 - energy * energy).sqrt();
        let exponentials = (0..moment_count)
            .map(|index| Complex64::from_polar(1.0, angle * index as f64))
            .collect::<Vec<_>>();
        for (channel, matrix) in moments.iter().enumerate() {
            let mut sum = Complex64::new(0.0, 0.0);
            for m in 0..moment_count {
                let tm = exponentials[m].re;
                for n in 0..moment_count {
                    let tn = exponentials[n].re;
                    let first = Complex64::new(energy, -(n as f64) * root) * exponentials[n] * tm;
                    let second =
                        Complex64::new(energy, (m as f64) * root) * exponentials[m].conj() * tn;
                    let wm = if m == 0 { weights[m] / 2.0 } else { weights[m] };
                    let wn = if n == 0 { weights[n] / 2.0 } else { weights[n] };
                    sum += matrix[m][n] * wm * wn * (first + second);
                }
            }
            result[sample][channel] = sum;
        }
    }
    Ok(result)
}

/// Integrates a Kubo-Bastin factor at chemical potential and temperature.
pub fn correlation_response(
    integral_factor: &[Vec<Complex64>],
    scale: SpectralScale,
    chemical_potential: f64,
    temperature: f64,
) -> Result<Vec<Complex64>, KpmError> {
    if temperature < 0.0
        || !temperature.is_finite()
        || !chemical_potential.is_finite()
        || integral_factor.len() < 2
        || integral_factor[0].is_empty()
    {
        return Err(KpmError::NonFiniteValue);
    }
    let channels = integral_factor[0].len();
    if integral_factor
        .iter()
        .any(|sample| sample.len() != channels)
    {
        return Err(KpmError::RaggedData);
    }
    let nodes = chebyshev_nodes(integral_factor.len())?;
    let mut integrands = vec![vec![Complex64::new(0.0, 0.0); channels]; nodes.len()];
    for (sample, &energy) in nodes.iter().enumerate() {
        let distribution = fermi_value(scale.physical(energy), chemical_potential, temperature);
        let weight = distribution / (1.0 - energy * energy).powi(2);
        for channel in 0..channels {
            integrands[sample][channel] = integral_factor[sample][channel] * weight;
        }
    }
    let mut result = simpson_nonuniform(&nodes, &integrands)?;
    let prefactor = 32.0 / (2.0 * scale.half_width()).powi(2);
    for value in &mut result {
        *value *= prefactor;
    }
    Ok(result)
}

/// Returns Jackson or Lorentz damping weights.
pub fn kernel_weights(moment_count: usize, kernel: Kernel) -> Result<Vec<f64>, KpmError> {
    if moment_count == 0 {
        return Err(KpmError::NoMoments);
    }
    match kernel {
        Kernel::Jackson => {
            let denominator = moment_count as f64 + 1.0;
            let angle = PI / denominator;
            Ok((0..moment_count)
                .map(|moment| {
                    let m = moment as f64;
                    ((denominator - m) * (angle * m).cos() + (angle * m).sin() / angle.tan())
                        / denominator
                })
                .collect())
        }
        Kernel::Lorentz(strength) => {
            if !strength.is_finite() || strength <= 0.0 {
                return Err(KpmError::NonFiniteValue);
            }
            Ok((0..moment_count)
                .map(|moment| {
                    (strength * (1.0 - moment as f64 / moment_count as f64)).sinh()
                        / strength.sinh()
                })
                .collect())
        }
        Kernel::None => Ok(vec![1.0; moment_count]),
    }
}

/// Applies a stabilization kernel along the first axis of a moment array.
pub fn apply_kernel(
    moments: &[Vec<Complex64>],
    kernel: Kernel,
) -> Result<Vec<Vec<Complex64>>, KpmError> {
    if moments.is_empty() {
        return Err(KpmError::NoMoments);
    }
    let components = moments[0].len();
    if components == 0 || moments.iter().any(|moment| moment.len() != components) {
        return Err(KpmError::RaggedData);
    }
    let weights = kernel_weights(moments.len(), kernel)?;
    Ok(moments
        .iter()
        .zip(weights)
        .map(|(moment, weight)| moment.iter().map(|value| value * weight).collect())
        .collect())
}

/// Returns ascending Chebyshev sampling nodes strictly inside `(-1, 1)`.
pub fn chebyshev_nodes(sample_count: usize) -> Result<Vec<f64>, KpmError> {
    if sample_count == 0 {
        return Err(KpmError::NoMoments);
    }
    Ok((0..sample_count)
        .map(|index| {
            let descending_index = sample_count - 1 - index;
            let angle = PI * (descending_index as f64 + 0.5) / sample_count as f64;
            angle.cos()
        })
        .collect())
}

/// Evaluates a Fermi-Dirac distribution.
pub fn fermi_distribution(
    energies: &[f64],
    chemical_potential: f64,
    temperature: f64,
) -> Result<Vec<f64>, KpmError> {
    if temperature < 0.0
        || !temperature.is_finite()
        || !chemical_potential.is_finite()
        || energies.iter().any(|energy| !energy.is_finite())
    {
        return Err(KpmError::NonFiniteValue);
    }
    Ok(energies
        .iter()
        .map(|energy| fermi_value(*energy, chemical_potential, temperature))
        .collect())
}

/// Constructs `i [H, X_direction]` from orbital positions.
pub fn velocity_operator(
    hamiltonian: &ComplexMatrix,
    positions: &[Vec<f64>],
    direction: usize,
) -> Result<ComplexMatrix, KpmError> {
    let dimension = validate_square(hamiltonian)?;
    if positions.len() != dimension
        || positions
            .iter()
            .any(|position| direction >= position.len() || !position[direction].is_finite())
    {
        return Err(KpmError::VectorDimension {
            expected: dimension,
            actual: positions.len(),
        });
    }
    let mut data = Vec::with_capacity(dimension * dimension);
    for row in 0..dimension {
        for column in 0..dimension {
            let displacement = positions[column][direction] - positions[row][direction];
            data.push(
                hamiltonian.as_slice()[row * dimension + column]
                    * Complex64::new(0.0, displacement),
            );
        }
    }
    ComplexMatrix::new(dimension, dimension, data).map_err(|_| KpmError::NonFiniteValue)
}

/// Constructs `i [H, X_direction]` while preserving CSR sparsity.
pub fn sparse_velocity_operator(
    hamiltonian: &CsrMatrix,
    positions: &[Vec<f64>],
    direction: usize,
) -> Result<CsrMatrix, KpmError> {
    let dimension = validate_operator_square(hamiltonian)?;
    validate_positions(positions, dimension, direction)?;
    let mut values = Vec::with_capacity(hamiltonian.nnz());
    for row in 0..dimension {
        for entry in hamiltonian.row_offsets()[row]..hamiltonian.row_offsets()[row + 1] {
            let column = hamiltonian.column_indices()[entry];
            let displacement = positions[column][direction] - positions[row][direction];
            values.push(hamiltonian.values()[entry] * Complex64::new(0.0, displacement));
        }
    }
    CsrMatrix::new(
        dimension,
        dimension,
        hamiltonian.row_offsets().to_vec(),
        hamiltonian.column_indices().to_vec(),
        values,
    )
    .map_err(KpmError::from)
}

fn spectral_scale(lower: f64, upper: f64, strict_margin: f64) -> Result<SpectralScale, KpmError> {
    if !strict_margin.is_finite() || strict_margin <= 0.0 || strict_margin >= 2.0 {
        return Err(KpmError::InvalidMargin);
    }
    if !lower.is_finite() || !upper.is_finite() || lower >= upper {
        return Err(KpmError::InvalidBounds);
    }
    let width = upper - lower;
    let tolerance = strict_margin * (upper + lower).abs().max(1.0) / 4.0;
    if width <= tolerance {
        return Err(KpmError::SingleEigenvalue);
    }
    SpectralScale::new(width / (2.0 - strict_margin), (upper + lower) / 2.0)
}

fn tridiagonal_extremes(
    alphas: &[f64],
    betas: &[f64],
    next_beta: f64,
) -> Result<SpectralBounds, KpmError> {
    let dimension = alphas.len();
    if dimension == 0 || betas.len() + 1 != dimension {
        return Err(KpmError::EigensystemFailure);
    }
    let mut matrix = DMatrix::<f64>::zeros(dimension, dimension);
    for (index, alpha) in alphas.iter().copied().enumerate() {
        matrix[(index, index)] = alpha;
    }
    for (index, beta) in betas.iter().copied().enumerate() {
        matrix[(index, index + 1)] = beta;
        matrix[(index + 1, index)] = beta;
    }
    let decomposition = SymmetricEigen::new(matrix);
    let (lower_index, &lower) = decomposition
        .eigenvalues
        .iter()
        .enumerate()
        .min_by(|(_, left), (_, right)| left.total_cmp(right))
        .ok_or(KpmError::EigensystemFailure)?;
    let (upper_index, &upper) = decomposition
        .eigenvalues
        .iter()
        .enumerate()
        .max_by(|(_, left), (_, right)| left.total_cmp(right))
        .ok_or(KpmError::EigensystemFailure)?;
    if !lower.is_finite() || !upper.is_finite() || !next_beta.is_finite() {
        return Err(KpmError::NonFiniteValue);
    }
    Ok(SpectralBounds {
        lower,
        upper,
        lower_residual: next_beta.abs()
            * decomposition.eigenvectors[(dimension - 1, lower_index)].abs(),
        upper_residual: next_beta.abs()
            * decomposition.eigenvectors[(dimension - 1, upper_index)].abs(),
        iterations: dimension,
        converged: false,
        breakdown: false,
    })
}

fn norm(vector: &[Complex64]) -> f64 {
    vector.iter().map(Complex64::norm_sqr).sum::<f64>().sqrt()
}

fn validate_operator_square<O: LinearOperator + ?Sized>(operator: &O) -> Result<usize, KpmError> {
    let (rows, columns) = operator.shape();
    if rows == 0 || rows != columns {
        Err(KpmError::InvalidHamiltonianShape { rows, columns })
    } else {
        Ok(rows)
    }
}

fn validate_square(matrix: &ComplexMatrix) -> Result<usize, KpmError> {
    validate_operator_square(matrix)
}

fn validate_vectors(vectors: &[Vec<Complex64>], dimension: usize) -> Result<(), KpmError> {
    for vector in vectors {
        if vector.len() != dimension {
            return Err(KpmError::VectorDimension {
                expected: dimension,
                actual: vector.len(),
            });
        }
        if vector
            .iter()
            .any(|value| !value.re.is_finite() || !value.im.is_finite())
        {
            return Err(KpmError::NonFiniteValue);
        }
    }
    Ok(())
}

fn validate_positions(
    positions: &[Vec<f64>],
    dimension: usize,
    direction: usize,
) -> Result<(), KpmError> {
    if positions.len() != dimension
        || positions
            .iter()
            .any(|position| direction >= position.len() || !position[direction].is_finite())
    {
        Err(KpmError::VectorDimension {
            expected: dimension,
            actual: positions.len(),
        })
    } else {
        Ok(())
    }
}

fn validate_chebyshev(values: &[Vec<Vec<Complex64>>]) -> Result<(usize, usize, usize), KpmError> {
    let vectors = values.len();
    let moments = values.first().map_or(0, Vec::len);
    let dimension = values
        .first()
        .and_then(|vector| vector.first())
        .map_or(0, Vec::len);
    if vectors == 0 || moments == 0 || dimension == 0 {
        return Err(KpmError::RaggedData);
    }
    if values.iter().any(|vector| {
        vector.len() != moments || vector.iter().any(|moment| moment.len() != dimension)
    }) {
        return Err(KpmError::RaggedData);
    }
    Ok((vectors, moments, dimension))
}

fn validate_moments(values: &[Vec<Vec<Complex64>>]) -> Result<(usize, usize, usize), KpmError> {
    validate_chebyshev(values)
}

fn validate_stabilized_moments(
    values: &[Vec<Vec<Complex64>>],
) -> Result<(usize, usize, usize), KpmError> {
    let moments = values.len();
    let channels = values.first().map_or(0, Vec::len);
    let components = values
        .first()
        .and_then(|moment| moment.first())
        .map_or(0, Vec::len);
    if moments == 0 || channels == 0 || components == 0 {
        return Err(KpmError::RaggedData);
    }
    if values.iter().any(|moment| {
        moment.len() != channels || moment.iter().any(|channel| channel.len() != components)
    }) {
        return Err(KpmError::RaggedData);
    }
    Ok((moments, channels, components))
}

fn inner(left: &[Complex64], right: &[Complex64]) -> Complex64 {
    left.iter()
        .zip(right)
        .map(|(left, right)| left.conj() * right)
        .sum()
}

fn evaluate_series(
    moments: &[Vec<Vec<Complex64>>],
    channel: usize,
    component: usize,
    energy: f64,
) -> Complex64 {
    let mut t_previous = 1.0;
    let mut result = moments[0][channel][component];
    if moments.len() == 1 {
        return result;
    }
    let mut t_current = energy;
    result += moments[1][channel][component] * (2.0 * t_current);
    for coefficients in moments.iter().skip(2) {
        let t_next = 2.0 * energy * t_current - t_previous;
        result += coefficients[channel][component] * (2.0 * t_next);
        t_previous = t_current;
        t_current = t_next;
    }
    result
}

fn fermi_value(energy: f64, chemical_potential: f64, temperature: f64) -> f64 {
    if temperature == 0.0 {
        f64::from(energy < chemical_potential)
    } else {
        let exponent = (energy - chemical_potential) / temperature;
        if exponent > 700.0 {
            0.0
        } else if exponent < -700.0 {
            1.0
        } else {
            1.0 / (1.0 + exponent.exp())
        }
    }
}

fn simpson_nonuniform(
    coordinates: &[f64],
    values: &[Vec<Complex64>],
) -> Result<Vec<Complex64>, KpmError> {
    let Some(first_row) = values.first() else {
        return Err(KpmError::RaggedData);
    };
    if coordinates.len() != values.len() || coordinates.len() < 2 || first_row.is_empty() {
        return Err(KpmError::RaggedData);
    }
    let channels = values[0].len();
    if values.iter().any(|row| row.len() != channels)
        || coordinates
            .windows(2)
            .any(|pair| !pair[0].is_finite() || pair[1] <= pair[0])
    {
        return Err(KpmError::RaggedData);
    }
    if coordinates.len() == 2 {
        let width = coordinates[1] - coordinates[0];
        return Ok((0..channels)
            .map(|channel| (values[0][channel] + values[1][channel]) * (width / 2.0))
            .collect());
    }

    let sample_count = coordinates.len();
    let regular_stop = if sample_count % 2 == 0 {
        sample_count - 3
    } else {
        sample_count - 2
    };
    let mut result = vec![Complex64::new(0.0, 0.0); channels];
    for first in (0..regular_stop).step_by(2) {
        let h0 = coordinates[first + 1] - coordinates[first];
        let h1 = coordinates[first + 2] - coordinates[first + 1];
        let sum = h0 + h1;
        let first_weight = sum / 6.0 * (2.0 - h1 / h0);
        let middle_weight = sum / 6.0 * (sum * sum / (h0 * h1));
        let last_weight = sum / 6.0 * (2.0 - h0 / h1);
        for (channel, integral) in result.iter_mut().enumerate() {
            *integral += values[first][channel] * first_weight
                + values[first + 1][channel] * middle_weight
                + values[first + 2][channel] * last_weight;
        }
    }

    if sample_count % 2 == 0 {
        let h0 = coordinates[sample_count - 2] - coordinates[sample_count - 3];
        let h1 = coordinates[sample_count - 1] - coordinates[sample_count - 2];
        let alpha = (2.0 * h1 * h1 + 3.0 * h0 * h1) / (6.0 * (h1 + h0));
        let beta = (h1 * h1 + 3.0 * h0 * h1) / (6.0 * h0);
        let eta = h1.powi(3) / (6.0 * h0 * (h0 + h1));
        for (channel, integral) in result.iter_mut().enumerate() {
            *integral += values[sample_count - 1][channel] * alpha
                + values[sample_count - 2][channel] * beta
                - values[sample_count - 3][channel] * eta;
        }
    }
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn diagonal(values: &[f64]) -> ComplexMatrix {
        let dimension = values.len();
        let mut matrix = ComplexMatrix::zeros(dimension, dimension);
        for (index, value) in values.iter().enumerate() {
            matrix
                .set(index, index, Complex64::new(*value, 0.0))
                .unwrap();
        }
        matrix
    }

    fn sparse_chain(dimension: usize) -> CsrMatrix {
        let mut offsets = Vec::with_capacity(dimension + 1);
        let mut columns = Vec::with_capacity(3 * dimension);
        let mut values = Vec::with_capacity(3 * dimension);
        offsets.push(0);
        for row in 0..dimension {
            if row > 0 {
                columns.push(row - 1);
                values.push(Complex64::new(-1.0, 0.0));
            }
            columns.push(row);
            values.push(Complex64::new(0.1 * (row % 3) as f64, 0.0));
            if row + 1 < dimension {
                columns.push(row + 1);
                values.push(Complex64::new(-1.0, 0.0));
            }
            offsets.push(values.len());
        }
        CsrMatrix::new(dimension, dimension, offsets, columns, values).unwrap()
    }

    #[test]
    fn rescaling_places_spectrum_strictly_inside_interval() {
        let rescaled = rescale_hamiltonian(&diagonal(&[-2.0, 1.0, 4.0]), 0.05, None).unwrap();
        let eigenvalues = hermitian_eigensystem(rescaled.matrix(), 1.0e-12).unwrap();
        assert!(eigenvalues
            .eigenvalues()
            .iter()
            .all(|value| value.abs() < 1.0));
        assert!((rescaled.scale().center() - 1.0).abs() < 1.0e-12);
    }

    #[test]
    fn chebyshev_vectors_match_polynomials_of_diagonal_hamiltonian() {
        let matrix = diagonal(&[-0.5, 0.25]);
        let vectors = chebyshev_vectors(
            &matrix,
            &[vec![Complex64::new(1.0, 0.0), Complex64::new(1.0, 0.0)]],
            4,
        )
        .unwrap();
        for (component, diagonal) in [-0.5, 0.25].iter().enumerate() {
            let x = *diagonal;
            assert!((vectors[0][2][component].re - (2.0 * x * x - 1.0)).abs() < 1.0e-12);
            assert!((vectors[0][3][component].re - (4.0 * x.powi(3) - 3.0 * x)).abs() < 1.0e-12);
        }
    }

    #[test]
    fn reconstructed_density_integrates_to_hilbert_space_dimension() {
        let hamiltonian = diagonal(&[-0.5, 0.5]);
        let rescaled = rescale_hamiltonian(&hamiltonian, 0.05, None).unwrap();
        let initial = vec![
            vec![Complex64::new(1.0, 0.0), Complex64::new(0.0, 0.0)],
            vec![Complex64::new(0.0, 0.0), Complex64::new(1.0, 0.0)],
        ];
        let vectors = chebyshev_vectors(rescaled.matrix(), &initial, 128).unwrap();
        let moments = scalar_moments(&initial, &vectors, None).unwrap();
        let reconstruction =
            reconstruct(&moments, rescaled.scale(), Kernel::Jackson, false).unwrap();
        let integrated = integrate(
            reconstruction.gammas(),
            &vec![1.0; reconstruction.energies().len()],
            rescaled.scale(),
        )
        .unwrap();
        let trace = integrated.iter().map(|channel| channel[0].re).sum::<f64>();
        assert!((trace - 2.0).abs() < 1.0e-10);
    }

    #[test]
    fn applying_a_kernel_preserves_extra_components() {
        let moments = vec![
            vec![Complex64::new(1.0, 0.0), Complex64::new(2.0, 0.0)],
            vec![Complex64::new(3.0, 0.0), Complex64::new(4.0, 0.0)],
        ];
        let damped = apply_kernel(&moments, Kernel::Jackson).unwrap();
        assert_eq!(damped.len(), 2);
        assert_eq!(damped[0].len(), 2);
        assert_eq!(damped[0], moments[0]);
        assert!(damped[1][0].re < moments[1][0].re);
    }

    #[test]
    fn velocity_is_the_position_commutator() {
        let hamiltonian = ComplexMatrix::new(
            2,
            2,
            vec![
                Complex64::new(0.0, 0.0),
                Complex64::new(-1.0, 0.0),
                Complex64::new(-1.0, 0.0),
                Complex64::new(0.0, 0.0),
            ],
        )
        .unwrap();
        let velocity = velocity_operator(&hamiltonian, &[vec![0.0], vec![2.0]], 0).unwrap();
        assert_eq!(velocity.as_slice()[1], Complex64::new(0.0, -2.0));
        assert_eq!(velocity.as_slice()[2], Complex64::new(0.0, 2.0));
        assert!(velocity.is_hermitian(1.0e-12).unwrap());
    }

    #[test]
    fn sparse_and_dense_recurrences_are_equivalent() {
        let dense = ComplexMatrix::new(
            4,
            4,
            vec![
                0.2.into(),
                (-1.0).into(),
                0.0.into(),
                Complex64::new(0.0, 0.3),
                (-1.0).into(),
                (-0.1).into(),
                (-0.7).into(),
                0.0.into(),
                0.0.into(),
                (-0.7).into(),
                0.4.into(),
                (-0.2).into(),
                Complex64::new(0.0, -0.3),
                0.0.into(),
                (-0.2).into(),
                0.6.into(),
            ],
        )
        .unwrap();
        let sparse = CsrMatrix::from_dense(&dense, 0.0).unwrap();
        let initial = vec![
            Complex64::new(1.0, 0.2),
            Complex64::new(-0.4, 0.7),
            Complex64::new(0.3, -0.1),
            Complex64::new(-0.2, -0.5),
        ];
        let dense_scaled = rescale_hamiltonian(&dense, 0.05, None).unwrap();
        let sparse_scaled = rescale_sparse_hamiltonian(sparse, 0.05, None, &initial).unwrap();
        assert!(
            (dense_scaled.scale().half_width() - sparse_scaled.scale().half_width()).abs()
                < 1.0e-10
        );
        assert!((dense_scaled.scale().center() - sparse_scaled.scale().center()).abs() < 1.0e-10);
        let dense_vectors =
            chebyshev_vectors(dense_scaled.matrix(), std::slice::from_ref(&initial), 32).unwrap();
        let sparse_vectors = chebyshev_vectors(&sparse_scaled, &[initial], 32).unwrap();
        for (dense_vector, sparse_vector) in dense_vectors[0]
            .iter()
            .flatten()
            .zip(sparse_vectors[0].iter().flatten())
        {
            assert!((*dense_vector - *sparse_vector).norm() < 1.0e-9);
        }
    }

    #[test]
    fn early_lanczos_breakdown_uses_safe_sparse_bounds() {
        let dense = diagonal(&[-10.0, 0.0, 7.0]);
        let sparse = CsrMatrix::from_dense(&dense, 0.0).unwrap();
        let scaled = rescale_sparse_hamiltonian(
            sparse,
            0.05,
            None,
            &[
                Complex64::new(0.0, 0.0),
                Complex64::new(1.0, 0.0),
                Complex64::new(0.0, 0.0),
            ],
        )
        .unwrap();
        for eigenvalue in [-10.0, 0.0, 7.0] {
            assert!(scaled.scale().rescale(eigenvalue).abs() < 1.0);
        }
    }

    #[test]
    fn large_sparse_recurrence_never_requires_dense_storage() {
        let dimension = 100_000;
        let sparse = sparse_chain(dimension);
        assert!(sparse.nnz() < 3 * dimension);
        let scaled = rescale_sparse_hamiltonian(
            sparse,
            0.05,
            Some((-2.1, 2.3)),
            &vec![Complex64::new(1.0, 0.0); dimension],
        )
        .unwrap();
        let mut initial = vec![Complex64::new(0.0, 0.0); dimension];
        initial[dimension / 2] = Complex64::new(1.0, 0.0);
        let vectors = chebyshev_vectors(&scaled, &[initial], 8).unwrap();
        assert_eq!(vectors[0].len(), 8);
        assert_eq!(vectors[0][0].len(), dimension);
        assert!(vectors[0]
            .iter()
            .flatten()
            .all(|value| value.re.is_finite() && value.im.is_finite()));
    }

    #[test]
    fn sparse_velocity_preserves_the_hamiltonian_sparsity_pattern() {
        let sparse = sparse_chain(5);
        let positions = (0..5).map(|index| vec![index as f64]).collect::<Vec<_>>();
        let velocity = sparse_velocity_operator(&sparse, &positions, 0).unwrap();
        assert_eq!(velocity.row_offsets(), sparse.row_offsets());
        assert_eq!(velocity.column_indices(), sparse.column_indices());
        assert_eq!(velocity.nnz(), sparse.nnz());
        assert!(velocity.is_hermitian(1.0e-12).unwrap());
    }

    #[test]
    fn irregular_simpson_rule_integrates_quadratics_exactly() {
        let coordinates = vec![-1.0, -0.4, 0.1, 0.45, 0.8, 1.0];
        let values = coordinates
            .iter()
            .map(|x| vec![Complex64::new(x * x, 0.0)])
            .collect::<Vec<_>>();
        let integral = simpson_nonuniform(&coordinates, &values).unwrap();
        assert!((integral[0].re - 2.0 / 3.0).abs() < 1.0e-12);
    }
}
